name: Benchmark

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  golang:
    name: Golang
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - run: go install golang.org/x/perf/cmd/benchstat@latest

      - run: go mod download -x
      - run: >
          go test
          -v -run=^$
          -count=10
          -bench=.
          -benchmem
          ./...
          | tee results.txt
      - run: benchstat results.txt | tee summary.txt

      - uses: actions/upload-artifact@v4
        with:
          name: golang
          path: |
            results.txt
            summary.txt

  cli:
    name: CLI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - run: sudo apt-get -y install fio hyperfine

      - run: mkdir -p db
      - run: fio .fio.ini

      - run: go mod download -x
      - run: go build -v ./cmd/summer

      - run: >
          hyperfine
          -w3
          --export-csv=sha256sum.csv
          --export-json=sha256sum.json
          --export-markdown=sha256sum.md
          'sha256sum db/*'

      - run: >
          hyperfine
          -w3
          --export-csv=summer.csv
          --export-json=summer.json
          --export-markdown=summer.md
          './summer generate db/*'
          './summer generate --open-file-jobs=8 --digest-jobs=8 db/*'

      - uses: actions/upload-artifact@v4
        with:
          name: cli
          path: |
            sha256sum.csv
            sha256sum.json
            sha256sum.md
            summer.csv
            summer.json
            summer.md
