name: CD

on:
  push:
    tags: [v*.*.*]

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin]
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - run: printf %s ${{ github.ref_name }} > cmd/summer/version.txt
      - run: go mod download -x
      - run: >
          env GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }}
          go build -v ./cmd/summer
      - run: >
          tar -vczf summer-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
          summer README.md NOTICE LICENSE

      - uses: actions/upload-artifact@v4
        with:
          # TODO: add a prefix to distinguish from changelog
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: summer-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}.tar.gz

  changelog:
    name: Changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: orhun/git-cliff-action@v4
        with:
          args: -vvl -sheader
          config: .cliff.toml
        env:
          OUTPUT: CHANGELOG.md

      - uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: CHANGELOG.md

  release:
    name: Release
    needs: [build, changelog]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: .

      - run: mv */*.tar.gz .
      - run: sha256sum *.tar.gz > sha256sums.txt

      - uses: softprops/action-gh-release@v2
        with:
          name: SUMMER ${{ github.ref_name }}
          body_path: changelog/CHANGELOG.md
          files: |
            *.tar.gz
            sha256sums.txt
